// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package inject

import (
	"gin-essential/logger"
	"gin-essential/repo/dao"
	"gin-essential/repo/dao/user"
	"gin-essential/router"
	"gin-essential/router/api"
	"gin-essential/srv/user"
)

// Injectors from wire.go:

// GenInjector ..
func GenInjector() (*Injector, func(), error) {
	db := dao.InitPgDB()
	user := &userdao.User{
		PgDB: db,
	}
	trans := &dao.Trans{
		DB: db,
	}
	usersrvUser := usersrv.User{
		UserDB: user,
		Trans:  trans,
	}
	apiUser := &api.User{
		UserSrv: usersrvUser,
	}
	routerRouter := &router.Router{
		UserAPI: apiUser,
	}
	engine := router.InitGinEngine(routerRouter)
	zapLogger := logger.InitLogger()
	injector := &Injector{
		Engine: engine,
		Logger: zapLogger,
	}
	return injector, func() {
	}, nil
}
